// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB9xA-7TyMtIYuovYQgY7Ccbiqa3rORx8M',
    appId: '1:119890044690:web:468a456415f8ea89f075cb',
    messagingSenderId: '119890044690',
    projectId: 'authentication-7684e',
    authDomain: 'authentication-7684e.firebaseapp.com',
    storageBucket: 'authentication-7684e.firebasestorage.app',
    measurementId: 'G-7DRXQCLVDG',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBFg8R30MmJ0s9CnRQX2jHLjzG5NEuTM5g',
    appId: '1:119890044690:android:f950f82ed960fe13f075cb',
    messagingSenderId: '119890044690',
    projectId: 'authentication-7684e',
    storageBucket: 'authentication-7684e.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDpjS07fXWOq16EiK_rDjYZ-QZ-BkJIFxM',
    appId: '1:119890044690:ios:af706aeed22f4961f075cb',
    messagingSenderId: '119890044690',
    projectId: 'authentication-7684e',
    storageBucket: 'authentication-7684e.firebasestorage.app',
    iosClientId: '119890044690-u5v8dlprm26ukbmb4r9b14app1618ach.apps.googleusercontent.com',
    iosBundleId: 'com.example.chatApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDpjS07fXWOq16EiK_rDjYZ-QZ-BkJIFxM',
    appId: '1:119890044690:ios:af706aeed22f4961f075cb',
    messagingSenderId: '119890044690',
    projectId: 'authentication-7684e',
    storageBucket: 'authentication-7684e.firebasestorage.app',
    iosClientId: '119890044690-u5v8dlprm26ukbmb4r9b14app1618ach.apps.googleusercontent.com',
    iosBundleId: 'com.example.chatApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB9xA-7TyMtIYuovYQgY7Ccbiqa3rORx8M',
    appId: '1:119890044690:web:61f6670fe39b0c41f075cb',
    messagingSenderId: '119890044690',
    projectId: 'authentication-7684e',
    authDomain: 'authentication-7684e.firebaseapp.com',
    storageBucket: 'authentication-7684e.firebasestorage.app',
    measurementId: 'G-QKYVLNH0PV',
  );
}
